/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tugaspertemuan3saddadnabbil;

import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author saddadnabbil
 */
public class LatihanSoal extends javax.swing.JFrame {

    /**
     * Creates new form LatihanSoal
     */
    public LatihanSoal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jeniskelamin = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        biodata = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nim = new javax.swing.JTextField();
        nama = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        lakiRadioButton = new javax.swing.JRadioButton();
        perempuanRadioButton = new javax.swing.JRadioButton();
        jurusan = new javax.swing.JComboBox<>();
        biaya = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        semester = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        nilkehadiran = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        niltugas = new javax.swing.JTextField();
        niluts = new javax.swing.JTextField();
        niluas = new javax.swing.JTextField();
        HitungButton = new javax.swing.JButton();
        HapusButton = new javax.swing.JButton();
        UpdateButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        nilaiPemrograman2 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        grade = new javax.swing.JTextField();
        daftarBiaya = new javax.swing.JPanel();
        reg = new javax.swing.JCheckBox();
        uas = new javax.swing.JCheckBox();
        uts = new javax.swing.JCheckBox();
        biayauts = new javax.swing.JTextField();
        biayareg = new javax.swing.JTextField();
        biayauas = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        outputFrame = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        rangkumanNilaiTable = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        biodata.setBackground(new java.awt.Color(255, 255, 102));
        biodata.setToolTipText("");

        jLabel2.setText("Nama");

        jLabel1.setText("NIM");

        jLabel3.setText("Jenis Kelamin");

        jLabel4.setText("Jurusan");

        jLabel5.setText("Biaya/bln");

        nim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nimActionPerformed(evt);
            }
        });

        jeniskelamin.add(lakiRadioButton);
        lakiRadioButton.setText("Laki-laki");
        lakiRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lakiRadioButtonActionPerformed(evt);
            }
        });

        jeniskelamin.add(perempuanRadioButton);
        perempuanRadioButton.setText("Perempuan");
        perempuanRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                perempuanRadioButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lakiRadioButton)
                    .addComponent(perempuanRadioButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lakiRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(perempuanRadioButton)
                .addContainerGap())
        );

        jurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "=== Pilih Jurusan ===", "Teknik Informatika", "Ekonomi", "MIPA" }));
        jurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jurusanActionPerformed(evt);
            }
        });

        jLabel6.setText("Semester");

        jLabel7.setText("Nilai Kehadiran");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel8.setText("Nilai Tugas");

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel9.setText("Nilai UTS");

        jLabel10.setText("NILAI UAS");

        niluas.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                niluasInputMethodTextChanged(evt);
            }
        });
        niluas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                niluasActionPerformed(evt);
            }
        });

        HitungButton.setText("HITUNG");
        HitungButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HitungButtonActionPerformed(evt);
            }
        });

        HapusButton.setBackground(new java.awt.Color(255, 51, 51));
        HapusButton.setForeground(new java.awt.Color(255, 255, 255));
        HapusButton.setText("HAPUS");
        HapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButtonActionPerformed(evt);
            }
        });

        UpdateButton.setText("UPDATE");
        UpdateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateButtonActionPerformed(evt);
            }
        });

        jLabel11.setText("Nilai Pemrograman II");

        nilaiPemrograman2.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                nilaiPemrograman2InputMethodTextChanged(evt);
            }
        });
        nilaiPemrograman2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nilaiPemrograman2ActionPerformed(evt);
            }
        });

        jLabel12.setText("Grade");

        grade.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                gradeInputMethodTextChanged(evt);
            }
        });
        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout biodataLayout = new javax.swing.GroupLayout(biodata);
        biodata.setLayout(biodataLayout);
        biodataLayout.setHorizontalGroup(
            biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodataLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(biodataLayout.createSequentialGroup()
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(45, 45, 45))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, biodataLayout.createSequentialGroup()
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)))
                .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nama)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jurusan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(biaya)
                    .addComponent(semester)
                    .addComponent(nim))
                .addGap(69, 69, 69)
                .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(biodataLayout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nilaiPemrograman2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, biodataLayout.createSequentialGroup()
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(niluts, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(niluas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, biodataLayout.createSequentialGroup()
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGap(54, 54, 54)
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nilkehadiran, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(niltugas)))
                    .addGroup(biodataLayout.createSequentialGroup()
                        .addComponent(UpdateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(HapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, biodataLayout.createSequentialGroup()
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(HitungButton, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 14, Short.MAX_VALUE))
        );
        biodataLayout.setVerticalGroup(
            biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(biodataLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(nilkehadiran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(niltugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(biodataLayout.createSequentialGroup()
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(niluts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(niluas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(15, 15, 15)
                .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(nilaiPemrograman2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(biodataLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(biaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(semester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addGroup(biodataLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(biodataLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(biodataLayout.createSequentialGroup()
                                .addComponent(HitungButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(UpdateButton)
                                .addContainerGap())
                            .addGroup(biodataLayout.createSequentialGroup()
                                .addComponent(HapusButton)
                                .addGap(20, 20, 20))))))
        );

        daftarBiaya.setBackground(new java.awt.Color(153, 153, 255));

        reg.setText("Reg.");
        reg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regActionPerformed(evt);
            }
        });

        uas.setText("UAS");
        uas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uasActionPerformed(evt);
            }
        });

        uts.setText("UTS");
        uts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                utsActionPerformed(evt);
            }
        });

        biayareg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                biayaregActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Daftar Biaya");

        javax.swing.GroupLayout daftarBiayaLayout = new javax.swing.GroupLayout(daftarBiaya);
        daftarBiaya.setLayout(daftarBiayaLayout);
        daftarBiayaLayout.setHorizontalGroup(
            daftarBiayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarBiayaLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(daftarBiayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(daftarBiayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(daftarBiayaLayout.createSequentialGroup()
                            .addComponent(reg)
                            .addGap(18, 18, 18)
                            .addComponent(biayareg))
                        .addGroup(daftarBiayaLayout.createSequentialGroup()
                            .addComponent(uts)
                            .addGap(18, 18, 18)
                            .addComponent(biayauts))
                        .addGroup(daftarBiayaLayout.createSequentialGroup()
                            .addComponent(uas)
                            .addGap(18, 18, 18)
                            .addComponent(biayauas, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        daftarBiayaLayout.setVerticalGroup(
            daftarBiayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(daftarBiayaLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(daftarBiayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reg)
                    .addComponent(biayareg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(daftarBiayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uts)
                    .addComponent(biayauts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(daftarBiayaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(uas)
                    .addComponent(biayauas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        outputFrame.setBackground(new java.awt.Color(102, 255, 102));

        output.setColumns(20);
        output.setRows(5);
        jScrollPane1.setViewportView(output);

        rangkumanNilaiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "NIM", "Nama", "Jenis Kelamin", "Semester", "Biaya", "Jurusan", "Nilai Pemrograman II", "Grade"
            }
        ));
        rangkumanNilaiTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rangkumanNilaiTableMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(rangkumanNilaiTable);

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Rangkuman Nilai");

        jLabel15.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Informasi Pribadi Data Terbaru");

        javax.swing.GroupLayout outputFrameLayout = new javax.swing.GroupLayout(outputFrame);
        outputFrame.setLayout(outputFrameLayout);
        outputFrameLayout.setHorizontalGroup(
            outputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputFrameLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(outputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 914, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        outputFrameLayout.setVerticalGroup(
            outputFrameLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(outputFrameLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(outputFrame, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(biodata, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(daftarBiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(biodata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(daftarBiaya, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(outputFrame, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lakiRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lakiRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lakiRadioButtonActionPerformed

    private void perempuanRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_perempuanRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_perempuanRadioButtonActionPerformed

    private void nimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nimActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nimActionPerformed

    private void biayaregActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_biayaregActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_biayaregActionPerformed

    private void regActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regActionPerformed
        // TODO add your handling code here:
        if (reg.isSelected()) {
            biayareg.setText("100000");
        } else {
            biayareg.setText("");
        }
    }//GEN-LAST:event_regActionPerformed

    private void HitungButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HitungButtonActionPerformed
        // TODO add your handling code here:
        String selectedGender = "";
        Enumeration<AbstractButton> genders = jeniskelamin.getElements();
        while (genders.hasMoreElements()) {
            AbstractButton genderButton = genders.nextElement();
            if (genderButton.isSelected()) {
                selectedGender = genderButton.getText();
                break;
            }
        }
        
        String selectedJurusan = "";
        if (jurusan.getSelectedItem() != null) {
            selectedJurusan = jurusan.getSelectedItem().toString();
            switch (selectedJurusan) {
                case "Teknik Informatika":
                    biaya.setText("300000");
                    break;
                case "Ekonomi":
                    biaya.setText("200000");
                    break;
                case "MIPA":
                    biaya.setText("225000");
                    break;
                default:
                    // Handle default case
                    break;
            }
        }

        int kehadiran, tugas, uts, uas;
        double pemrograman;

        kehadiran = Integer.parseInt(nilkehadiran.getText());
        tugas = Integer.parseInt(niltugas.getText());
        uts = Integer.parseInt(niluts.getText());
        uas = Integer.parseInt(niluas.getText());
        
        pemrograman = 0.1 * kehadiran + 0.2 * tugas + 0.3 * uts + 0.4 * uas;
        
        String gradePemrograman;
        if (pemrograman < 50) {
            gradePemrograman = "E";
        } else if (pemrograman < 60) {
            gradePemrograman = "D";
        } else if (pemrograman < 70) {
            gradePemrograman = "C";
        } else if (pemrograman < 80) {
            gradePemrograman = "B";
        } else {
            gradePemrograman = "A";
        }
        
        if (jurusan.getSelectedItem() != null) {
        selectedJurusan = jurusan.getSelectedItem().toString();
            switch (selectedJurusan) {
                case "Teknik Informatika":
                    biaya.setText("300000");
                    break;
                case "Ekonomi":
                    biaya.setText("200000");
                    break;
                case "MIPA":
                    biaya.setText("225000");
                    break;
                default:
                    biaya.setText("");
                    break;
            }
        }
        
        output.setText(
            "NIM \t: " + nim.getText() +
            "\nNama\t: " + nama.getText() +
            "\nJenis Kelamin\t: " + selectedGender +
            "\nJurusan\t: " + selectedJurusan +   
            "\nSemester\t: " + semester.getText() +
            "\nBiaya\t: " + biaya.getText()
        );
        
        DefaultTableModel model = (DefaultTableModel) rangkumanNilaiTable.getModel();
        String[] rowData = {
            nim.getText(),
            nama.getText(),
            selectedGender,
            semester.getText(),
            selectedJurusan,
            biaya.getText(),
            String.valueOf(pemrograman), 
            gradePemrograman
        };
        model.addRow(rowData);
    }//GEN-LAST:event_HitungButtonActionPerformed

    private void jurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jurusanActionPerformed
        // TODO add your handling code here:
        String selectedJurusan = "";
        if (jurusan.getSelectedItem() != null) {
            selectedJurusan = jurusan.getSelectedItem().toString();
            switch (selectedJurusan) {
                case "Teknik Informatika":
                    biaya.setText("300000");
                    break;
                case "Ekonomi":
                    biaya.setText("200000");
                    break;
                case "MIPA":
                    biaya.setText("225000");
                    break;
                default:
                    biaya.setText("");
                    break;
            }
        }
    }//GEN-LAST:event_jurusanActionPerformed

    private void niluasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_niluasActionPerformed
        
    }//GEN-LAST:event_niluasActionPerformed

    private void niluasInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_niluasInputMethodTextChanged

    }//GEN-LAST:event_niluasInputMethodTextChanged

    private void utsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_utsActionPerformed
        // TODO add your handling code here:
        if (uts.isSelected()) {
            biayauts.setText("300000");
        } else {
            biayauts.setText("");
        }
    }//GEN-LAST:event_utsActionPerformed

    private void uasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uasActionPerformed
        // TODO add your handling code here:
        if (uas.isSelected()) {
            biayauas.setText("300000");
        } else {
            biayauas.setText("");
        }
    }//GEN-LAST:event_uasActionPerformed

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
        // TODO add your handling code here:
        nim.setText("");
        nama.setText("");
        jeniskelamin.clearSelection(); 
        jurusan.setSelectedIndex(-1);
        semester.setText("");
        biaya.setText("");
        nilkehadiran.setText("");
        niltugas.setText("");
        niluts.setText("");
        niluas.setText("");
        output.setText("");
        
        DefaultTableModel dataModel = (DefaultTableModel) rangkumanNilaiTable.getModel();    
        if (rangkumanNilaiTable.getRowCount() > 0) {
            for (int i = rangkumanNilaiTable.getRowCount() - 1; i > -1; i--) {
                dataModel.removeRow(i);
            }
        }
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void UpdateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = rangkumanNilaiTable.getSelectedRow();
        if (selectedRow == -1) { // Jika tidak ada baris yang dipilih
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diperbarui.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return; // Keluar dari method untuk menghentikan pembaruan
        }
        if (selectedRow != -1) { // Pastikan ada baris yang dipilih
            DefaultTableModel model = (DefaultTableModel) rangkumanNilaiTable.getModel();
            model.setValueAt(nim.getText(), selectedRow, 0);
            model.setValueAt(nama.getText(), selectedRow, 1);
            // Mengambil nilai dari radio button jenis kelamin
            String selectedGender = "";
            if (lakiRadioButton.isSelected()) {
                selectedGender = "Laki-laki";
            } else if (perempuanRadioButton.isSelected()) {
                selectedGender = "Perempuan";
            }
            model.setValueAt(selectedGender, selectedRow, 2);
            model.setValueAt(semester.getText(), selectedRow, 3);
            model.setValueAt(jurusan.getSelectedItem().toString(), selectedRow, 4);
            model.setValueAt(biaya.getText(), selectedRow, 5);
            model.setValueAt(nilaiPemrograman2.getText(), selectedRow, 6);
            model.setValueAt(grade.getText(), selectedRow, 7);
            
            // Set teks output dengan nilai yang diperbarui
            output.setText(
                "NIM \t: " + nim.getText() +
                "\nNama\t: " + nama.getText() +
                "\nJenis Kelamin\t: " + selectedGender +
                "\nJurusan\t: " + jurusan.getSelectedItem().toString() +
                "\nSemester\t: " + semester.getText() +
                "\nBiaya\t: " + biaya.getText()
            );
    
            // Tampilkan pesan berhasil
            JOptionPane.showMessageDialog(this, "Data berhasil diperbarui.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_UpdateButtonActionPerformed

    private void rangkumanNilaiTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rangkumanNilaiTableMouseClicked
        // TODO add your handling code here:
        int selectedRow = rangkumanNilaiTable.getSelectedRow();
        if (selectedRow != -1) { // -1 berarti tidak ada baris yang dipilih
            DefaultTableModel model = (DefaultTableModel) rangkumanNilaiTable.getModel();
            nim.setText(model.getValueAt(selectedRow, 0).toString());
            nama.setText(model.getValueAt(selectedRow, 1).toString());
            String gender = model.getValueAt(selectedRow, 2).toString();
            // Untuk memilih radio button berdasarkan jenis kelamin
            if (gender.equals("Laki-laki")) {
                lakiRadioButton.setSelected(true);
            } else if (gender.equals("Perempuan")) {
                perempuanRadioButton.setSelected(true);
            }
            semester.setText(model.getValueAt(selectedRow, 3).toString());
            jurusan.setSelectedItem(model.getValueAt(selectedRow, 4).toString());
            biaya.setText(model.getValueAt(selectedRow, 5).toString());
            nilaiPemrograman2.setText(model.getValueAt(selectedRow, 6).toString());
            grade.setText(model.getValueAt(selectedRow, 7).toString());
            // Mengosongkan text field yang tidak ada dalam tabel
            nilkehadiran.setText("");
            niltugas.setText("");
            niluts.setText("");
            niluas.setText("");
            output.setText("");
        }
    }//GEN-LAST:event_rangkumanNilaiTableMouseClicked

    private void nilaiPemrograman2InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_nilaiPemrograman2InputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiPemrograman2InputMethodTextChanged

    private void nilaiPemrograman2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nilaiPemrograman2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nilaiPemrograman2ActionPerformed

    private void gradeInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_gradeInputMethodTextChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeInputMethodTextChanged

    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeActionPerformed

   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LatihanSoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LatihanSoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LatihanSoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LatihanSoal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LatihanSoal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton HapusButton;
    private javax.swing.JButton HitungButton;
    private javax.swing.JButton UpdateButton;
    private javax.swing.JTextField biaya;
    private javax.swing.JTextField biayareg;
    private javax.swing.JTextField biayauas;
    private javax.swing.JTextField biayauts;
    private javax.swing.JPanel biodata;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel daftarBiaya;
    private javax.swing.JTextField grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.ButtonGroup jeniskelamin;
    private javax.swing.JComboBox<String> jurusan;
    private javax.swing.JRadioButton lakiRadioButton;
    private javax.swing.JTextField nama;
    private javax.swing.JTextField nilaiPemrograman2;
    private javax.swing.JTextField nilkehadiran;
    private javax.swing.JTextField niltugas;
    private javax.swing.JTextField niluas;
    private javax.swing.JTextField niluts;
    private javax.swing.JTextField nim;
    private javax.swing.JTextArea output;
    private javax.swing.JPanel outputFrame;
    private javax.swing.JRadioButton perempuanRadioButton;
    private javax.swing.JTable rangkumanNilaiTable;
    private javax.swing.JCheckBox reg;
    private javax.swing.JTextField semester;
    private javax.swing.JCheckBox uas;
    private javax.swing.JCheckBox uts;
    // End of variables declaration//GEN-END:variables
}
